# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='martialart',
            options={'verbose_name': 'Marial Art', 'verbose_name_plural': 'Martial Arts'},
        ),
    ]
