# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld2', '0002_auto_20151208_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='test',
            field=models.CharField(default='Hi!', max_length=200),
        ),
    ]
